-- 1. Limpieza (Reset)
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS users; -- Nota: Esto borra la tabla 'users' pública, no el auth.users del sistema
DROP FUNCTION IF EXISTS handle_new_user CASCADE;

-- 2. Tabla de Usuarios (Perfiles Públicos)
-- Sincronizada con la tabla interna de Supabase (auth.users)
CREATE TABLE public.users (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY, -- Enlace directo a Auth
  email TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (Seguridad por Filas)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Politicas de Seguridad para Usuarios
-- "Cualquiera puede ver los perfiles" (necesario para login basico en frontend)
CREATE POLICY "Public profiles are viewable by everyone" ON public.users FOR SELECT USING (true);
-- "El usuario puede actualizar su propio perfil"
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = id);

-- 3. Tabla de Noticias
CREATE TABLE public.news (
    news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    author_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Ahora usa UUID
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- Politicas de Seguridad para Noticias
-- "Cualquiera puede ver noticias"
CREATE POLICY "News are viewable by everyone" ON public.news FOR SELECT USING (true);

-- "Solo admins pueden insertar/editar/borrar"
-- (Para simplificar, aquí permitimos a usuarios logueados, pero en tu JS controlas el rol. 
--  Para mayor seguridad, usaríamos una función que chequee el rol de la tabla users)
CREATE POLICY "Authenticated users can create news" ON public.news FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update news" ON public.news FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete news" ON public.news FOR DELETE USING (auth.role() = 'authenticated');

-- 4. Automatización (Trigger)
-- Cada vez que alguien se registra en Supabase Auth, se crea una fila en public.users automáticamente
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, role)
  VALUES (new.id, new.email, 'user'); -- Por defecto 'user'
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. Insertar Datos de Prueba (Opcional)
-- Nota: Para insertar usuarios tendrías primero que crearlos en el panel de Auth de Supabase (Authentication -> Users)
-- Así que insertaremos solo una noticia de ejemplo con author_id NULL por ahora para evitar errores de FK
INSERT INTO public.news (title, content, published_at) 
VALUES ('Bienvenido a Vortex con Supabase', 'Esta noticia viene directamente de tu nueva base de datos en la nube.', NOW());
