-- ==============================================================================
-- VORTEX RPA WEB - INITIALIZATION SCRIPT (CONSOLIDATED)
-- Includes: Users, News, Bots, Incidents, Subscriptions, History, Logs, Storage
-- Security: RLS, Admin Roles, Triggers
-- ==============================================================================

-- 1. CLEANUP (RESET)
-- Be careful: This drops all your data!
DROP TABLE IF EXISTS public.notification_log;
DROP TABLE IF EXISTS public.bot_status_history;
DROP TABLE IF EXISTS public.incidents;
DROP TABLE IF EXISTS public.bots;
DROP TABLE IF EXISTS public.subscriptions;
DROP TABLE IF EXISTS public.news;
DROP TABLE IF EXISTS public.users;
DROP FUNCTION IF EXISTS public.handle_new_user CASCADE;
DROP FUNCTION IF EXISTS public.is_admin CASCADE;
DROP FUNCTION IF EXISTS public.update_updated_at_column CASCADE;
DROP FUNCTION IF EXISTS public.log_bot_status_change CASCADE;

-- 2. USERS & AUTHENTICATION
-- Synced with Supabase auth.users
CREATE TABLE public.users (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone" ON public.users FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = id);

-- Helper function to check admin role
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to create public.users profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, role)
  VALUES (new.id, new.email, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 3. NEWS SYSTEM
CREATE TABLE public.news (
    news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    category TEXT CHECK (category IN ('Bots', 'Incidentes', 'Mejoras', 'Release', 'Comunicados')) DEFAULT 'Comunicados',
    tags TEXT[] DEFAULT '{}',
    is_featured BOOLEAN DEFAULT false,
    priority INTEGER DEFAULT 0,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    author_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- News Policies
CREATE POLICY "News are viewable by everyone" ON public.news FOR SELECT USING (true);
-- Only Admins can manage news
CREATE POLICY "Admins can create news" ON public.news FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "Admins can update news" ON public.news FOR UPDATE USING (is_admin());
CREATE POLICY "Admins can delete news" ON public.news FOR DELETE USING (is_admin());


-- 4. BOTS MONITORING SYSTEM
CREATE TABLE public.bots (
    bot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    system TEXT NOT NULL, -- SAP, DIAN, etc.
    environment TEXT CHECK (environment IN ('Producción', 'Desarrollo', 'QA')) NOT NULL,
    client TEXT, -- Added in v1.1
    status TEXT CHECK (status IN ('operativo', 'observacion', 'caido')) DEFAULT 'operativo' NOT NULL,
    responsible_name TEXT,
    responsible_email TEXT,
    last_status_update TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.bots ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_bots_status ON public.bots(status);
CREATE INDEX IF NOT EXISTS idx_bots_client ON public.bots(client);

-- Bots Policies
CREATE POLICY "Bots are viewable by everyone" ON public.bots FOR SELECT USING (true);
CREATE POLICY "Admins can insert bots" ON public.bots FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "Admins can update bots" ON public.bots FOR UPDATE USING (is_admin());
CREATE POLICY "Admins can delete bots" ON public.bots FOR DELETE USING (is_admin());


-- 5. BOT STATUS HISTORY
CREATE TABLE public.bot_status_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT REFERENCES public.bots(bot_id) ON DELETE CASCADE NOT NULL,
    previous_status TEXT,
    new_status TEXT NOT NULL,
    changed_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT
);

ALTER TABLE public.bot_status_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Bot history viewable by everyone" ON public.bot_status_history FOR SELECT USING (true);
-- System or Admins create history
CREATE POLICY "Admins can create history" ON public.bot_status_history FOR INSERT WITH CHECK (is_admin() OR auth.role() = 'authenticated');


-- 6. INCIDENTS SYSTEM
CREATE TABLE public.incidents (
    incident_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT REFERENCES public.bots(bot_id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    impact TEXT CHECK (impact IN ('Bajo', 'Medio', 'Alto', 'Crítico')) NOT NULL,
    status TEXT CHECK (status IN ('Abierto', 'En Progreso', 'Resuelto', 'Cerrado')) DEFAULT 'Abierto' NOT NULL,
    root_cause TEXT,
    resolution TEXT,
    lessons_learned TEXT,
    reported_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_incidents_bot ON public.incidents(bot_id);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON public.incidents(status);

-- Incidents Policies
CREATE POLICY "Incidents are viewable by everyone" ON public.incidents FOR SELECT USING (true);
CREATE POLICY "Admins can insert incidents" ON public.incidents FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "Admins can update incidents" ON public.incidents FOR UPDATE USING (is_admin());
CREATE POLICY "Admins can delete incidents" ON public.incidents FOR DELETE USING (is_admin());


-- 7. SUBSCRIPTIONS SYSTEM
CREATE TABLE public.subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    subscription_type TEXT[] DEFAULT '{}', -- ['news', 'bot_status', 'incidents']
    news_categories TEXT[] DEFAULT '{}',
    push_subscription JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Subscriptions Policies (Users manage their own)
CREATE POLICY "Users can view own subscription" ON public.subscriptions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own subscription" ON public.subscriptions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own subscription" ON public.subscriptions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own subscription" ON public.subscriptions FOR DELETE USING (auth.uid() = user_id);


-- 8. NOTIFICATION LOG
CREATE TABLE public.notification_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT REFERENCES public.subscriptions(subscription_id) ON DELETE CASCADE,
    notification_type TEXT NOT NULL,
    channel TEXT NOT NULL, -- 'push', 'email'
    status TEXT DEFAULT 'pending',
    error_message TEXT,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.notification_log ENABLE ROW LEVEL SECURITY;


-- 9. TRIGGERS & AUTOMATION

-- Function to auto-update 'updated_at'
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_bots_updated_at BEFORE UPDATE ON public.bots FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_incidents_updated_at BEFORE UPDATE ON public.incidents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_subscriptions_updated_at BEFORE UPDATE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Function to log bot status changes
CREATE OR REPLACE FUNCTION log_bot_status_change()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO public.bot_status_history (bot_id, previous_status, new_status, notes, changed_by)
        VALUES (NEW.bot_id, OLD.status, NEW.status, 'Cambio de estado detectado', auth.uid());
        
        NEW.last_status_update = timezone('utc'::text, now());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER bot_status_change_trigger BEFORE UPDATE ON public.bots FOR EACH ROW EXECUTE FUNCTION log_bot_status_change();


-- 10. STORAGE CONFIGURATION
-- Bucket: news-images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('news-images', 'news-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'news-images' );
CREATE POLICY "Auth Uploads" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'news-images' AND auth.role() = 'authenticated' );
CREATE POLICY "Auth Updates" ON storage.objects FOR UPDATE USING ( bucket_id = 'news-images' AND auth.role() = 'authenticated' );
CREATE POLICY "Auth Deletes" ON storage.objects FOR DELETE USING ( bucket_id = 'news-images' AND auth.role() = 'authenticated' );


-- 11. SAMPLE DATA
INSERT INTO public.news (title, content, published_at, category, priority, is_featured) 
VALUES ('Sistema Vortex Iniciado', 'La plataforma ha sido migrada exitosamente a la nueva arquitectura.', NOW(), 'Comunicados', 1, true);

INSERT INTO public.bots (name, description, system, environment, client, status) VALUES
('Bot Facturación', 'Proceso de facturación automática', 'SAP', 'Producción', 'Interno', 'operativo'),
('Bot Conciliación', 'Conciliación bancaria diaria', 'SAP', 'Producción', 'Cliente A', 'operativo'),
('Bot Reportes', 'Generación de reportes de cierre', 'PowerBi', 'Producción', 'Cliente B', 'caido');

-- 12. TIME ENTRIES (RPA Activities)
CREATE TABLE public.time_entries (
    id BIGINT PRIMARY KEY, -- ID from Excel
    date DATE, -- Allow nulls as per user request
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    project_name TEXT,
    user_full_name TEXT,
    description TEXT,
    project_category TEXT,
    company TEXT,
    task_list TEXT,
    task_name TEXT,
    parent_task TEXT,
    is_sub_task BOOLEAN DEFAULT false,
    is_billable BOOLEAN DEFAULT false,
    invoice_number TEXT,
    hours INTEGER,
    minutes INTEGER,
    decimal_hours NUMERIC(10, 2),
    estimated_time NUMERIC(10, 2),
    estimated_hours NUMERIC(10, 2),
    estimated_minutes NUMERIC(10, 2),
    tags TEXT,
    task_tags TEXT,
    first_name TEXT,
    last_name TEXT,
    external_user_id BIGINT,
    external_task_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.time_entries ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Time entries viewable by everyone" ON public.time_entries FOR SELECT USING (true);
CREATE POLICY "Admins can manage entries" ON public.time_entries FOR ALL USING (is_admin());

-- 13. VIEWS FOR DASHBOARD
-- View 1: Hours per day per person
CREATE OR REPLACE VIEW public.daily_hours_by_person AS
SELECT 
    date,
    last_name,
    SUM(decimal_hours) as total_hours
FROM 
    public.time_entries
GROUP BY 
    date, last_name
ORDER BY 
    date DESC, last_name;

-- View 2: Hours per task tag per day
CREATE OR REPLACE VIEW public.daily_tag_hours AS
SELECT 
    date,
    task_tags,
    SUM(decimal_hours) as total_hours
FROM 
    public.time_entries
WHERE 
    task_tags IS NOT NULL
GROUP BY 
    date, task_tags;

-- View 3: Hours per person per tag per day
CREATE OR REPLACE VIEW public.daily_person_tag_hours AS
SELECT 
    date,
    last_name,
    task_tags,
    SUM(decimal_hours) as tag_hours
FROM 
    public.time_entries
WHERE 
    task_tags IS NOT NULL
GROUP BY 
    date, last_name, task_tags;




