-- Migration: Bot Monitoring System with Incidents and Subscriptions

-- 1. Tabla de Bots/Procesos
CREATE TABLE IF NOT EXISTS public.bots (
    bot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT CHECK (status IN ('operativo', 'observacion', 'caido')) DEFAULT 'operativo',
    last_status_update TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    responsible_user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    responsible_name TEXT, -- Nombre del responsable para display
    responsible_email TEXT,
    system TEXT, -- Sistema al que pertenece (ej: SAP, DIAN, etc.)
    environment TEXT CHECK (environment IN ('Producción', 'Desarrollo', 'QA')) DEFAULT 'Producción',
    related_news_id BIGINT REFERENCES public.news(news_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Historial de Estados de Bots
CREATE TABLE IF NOT EXISTS public.bot_status_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT REFERENCES public.bots(bot_id) ON DELETE CASCADE NOT NULL,
    previous_status TEXT,
    new_status TEXT NOT NULL,
    changed_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT,
    related_news_id BIGINT REFERENCES public.news(news_id) ON DELETE SET NULL
);

-- 3. Tabla de Incidentes
CREATE TABLE IF NOT EXISTS public.incidents (
    incident_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT REFERENCES public.bots(bot_id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    impact_level TEXT CHECK (impact_level IN ('Bajo', 'Medio', 'Alto', 'Crítico')) DEFAULT 'Medio',
    root_cause TEXT,
    resolution TEXT,
    lessons_learned TEXT,
    status TEXT CHECK (status IN ('Abierto', 'En Progreso', 'Resuelto', 'Cerrado')) DEFAULT 'Abierto',
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    reported_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    assigned_to UUID REFERENCES public.users(id) ON DELETE SET NULL,
    related_news_id BIGINT REFERENCES public.news(news_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabla de Suscripciones
CREATE TABLE IF NOT EXISTS public.subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    email TEXT NOT NULL,
    
    -- Tipos de suscripción
    subscribe_news BOOLEAN DEFAULT false,
    subscribe_bot_status BOOLEAN DEFAULT false,
    subscribe_incidents BOOLEAN DEFAULT false,
    
    -- Suscripciones específicas
    news_categories TEXT[], -- Array de categorías de noticias
    specific_bots BIGINT[], -- Array de IDs de bots específicos
    
    -- Canales de notificación
    notify_email BOOLEAN DEFAULT true,
    notify_teams BOOLEAN DEFAULT false,
    teams_webhook_url TEXT,
    
    -- Configuración
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    UNIQUE(user_id) -- Un usuario solo puede tener una configuración de suscripción
);

-- 5. Tabla de Notificaciones Enviadas (Log)
CREATE TABLE IF NOT EXISTS public.notification_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT REFERENCES public.subscriptions(subscription_id) ON DELETE CASCADE,
    notification_type TEXT NOT NULL, -- 'news', 'bot_status', 'incident'
    reference_id BIGINT, -- ID de la noticia, bot o incidente
    channel TEXT NOT NULL, -- 'email', 'teams'
    status TEXT CHECK (status IN ('pending', 'sent', 'failed')) DEFAULT 'pending',
    error_message TEXT,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para mejor rendimiento
CREATE INDEX IF NOT EXISTS idx_bots_status ON public.bots(status);
CREATE INDEX IF NOT EXISTS idx_bots_system ON public.bots(system);
CREATE INDEX IF NOT EXISTS idx_bots_environment ON public.bots(environment);
CREATE INDEX IF NOT EXISTS idx_bot_status_history_bot ON public.bot_status_history(bot_id);
CREATE INDEX IF NOT EXISTS idx_incidents_bot ON public.incidents(bot_id);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON public.incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_impact ON public.incidents(impact_level);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_notification_log_subscription ON public.notification_log(subscription_id);

-- Row Level Security
ALTER TABLE public.bots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_log ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad

-- Bots: Todos pueden ver, solo admins pueden modificar
CREATE POLICY "Bots are viewable by everyone" ON public.bots FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create bots" ON public.bots FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update bots" ON public.bots FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete bots" ON public.bots FOR DELETE USING (auth.role() = 'authenticated');

-- Historial: Todos pueden ver, solo admins pueden crear
CREATE POLICY "Bot history viewable by everyone" ON public.bot_status_history FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create history" ON public.bot_status_history FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Incidentes: Todos pueden ver, solo admins pueden modificar
CREATE POLICY "Incidents viewable by everyone" ON public.incidents FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create incidents" ON public.incidents FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update incidents" ON public.incidents FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete incidents" ON public.incidents FOR DELETE USING (auth.role() = 'authenticated');

-- Suscripciones: Los usuarios solo pueden ver y modificar las suyas
CREATE POLICY "Users can view own subscriptions" ON public.subscriptions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own subscriptions" ON public.subscriptions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own subscriptions" ON public.subscriptions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own subscriptions" ON public.subscriptions FOR DELETE USING (auth.uid() = user_id);

-- Log de notificaciones: Solo lectura para usuarios autenticados
CREATE POLICY "Notification log viewable by authenticated" ON public.notification_log FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "System can create notification logs" ON public.notification_log FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Función para actualizar timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers para actualizar updated_at
DROP TRIGGER IF EXISTS update_bots_updated_at ON public.bots;
CREATE TRIGGER update_bots_updated_at
    BEFORE UPDATE ON public.bots
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_incidents_updated_at ON public.incidents;
CREATE TRIGGER update_incidents_updated_at
    BEFORE UPDATE ON public.incidents
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_subscriptions_updated_at ON public.subscriptions;
CREATE TRIGGER update_subscriptions_updated_at
    BEFORE UPDATE ON public.subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger para registrar cambios de estado en historial
CREATE OR REPLACE FUNCTION log_bot_status_change()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO public.bot_status_history (bot_id, previous_status, new_status, notes)
        VALUES (NEW.bot_id, OLD.status, NEW.status, 'Estado actualizado');
        
        NEW.last_status_update = timezone('utc'::text, now());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bot_status_change_trigger ON public.bots;
CREATE TRIGGER bot_status_change_trigger
    BEFORE UPDATE ON public.bots
    FOR EACH ROW
    EXECUTE FUNCTION log_bot_status_change();

-- Datos de ejemplo
INSERT INTO public.bots (name, description, status, system, environment, responsible_name, responsible_email) VALUES
('Bot Facturación SAP', 'Automatización de facturación en SAP', 'operativo', 'SAP', 'Producción', 'Juan Pérez', 'juan.perez@empresa.com'),
('Bot Validación DIAN', 'Validación de documentos en DIAN', 'observacion', 'DIAN', 'Producción', 'María García', 'maria.garcia@empresa.com'),
('Bot Conciliación Bancaria', 'Conciliación automática de cuentas', 'operativo', 'SAP', 'Producción', 'Carlos López', 'carlos.lopez@empresa.com'),
('Bot Reportes Power BI', 'Generación de reportes automáticos', 'caido', 'Power BI', 'Producción', 'Ana Martínez', 'ana.martinez@empresa.com');

-- Comentarios
COMMENT ON TABLE public.bots IS 'Tabla de bots/procesos automatizados';
COMMENT ON TABLE public.bot_status_history IS 'Historial de cambios de estado de bots';
COMMENT ON TABLE public.incidents IS 'Registro de incidentes relacionados con bots';
COMMENT ON TABLE public.subscriptions IS 'Configuración de suscripciones de usuarios';
COMMENT ON TABLE public.notification_log IS 'Log de notificaciones enviadas';
